### ISSUE TITLE
Error with custom build step

### ISSUE THREAD

**Issue by Quantumplation** [OctopusDeploy/OctoTFS#12]
I received this error while attempting to run the custom build step on TFS:

    2015-08-25T17:42:24.4172512Z Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
    2015-08-25T17:42:24.4172512Z    at Newtonsoft.Json.JsonTextReader.ParseValue()
    2015-08-25T17:42:24.4182512Z    at Newtonsoft.Json.JsonTextReader.ReadInternal()
    2015-08-25T17:42:24.4182512Z    at Newtonsoft.Json.JsonTextReader.Read()
    2015-08-25T17:42:24.4192512Z    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
    2015-08-25T17:42:24.4192512Z    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
    2015-08-25T17:42:24.4192512Z    at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
    2015-08-25T17:42:24.4202512Z    at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
    2015-08-25T17:42:24.4202512Z    at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
    2015-08-25T17:42:24.4212512Z    at Octopus.Client.OctopusClient.DispatchRequest[TResponseResource](OctopusRequest request, Boolean readResponse)
    2015-08-25T17:42:24.4212512Z    at Octopus.Client.OctopusClient.Get[TResource](String path, Object pathParameters)
    2015-08-25T17:42:24.4222512Z    at Octopus.Client.OctopusClient.EstablishSession()
    2015-08-25T17:42:24.4222512Z    at System.Lazy`1.CreateValue()
    2015-08-25T17:42:24.4232512Z    at System.Lazy`1.LazyInitValue()
    2015-08-25T17:42:24.4232512Z    at System.Lazy`1.get_Value()
    2015-08-25T17:42:24.4242512Z    at Octopus.Client.OctopusClient.get_RootDocument()
    2015-08-25T17:42:24.4242512Z    at OctopusTools.Commands.ApiCommand.Execute(String[] commandLineArguments)
    2015-08-25T17:42:24.4252512Z    at OctopusTools.Program.Main(String[] args)
    2015-08-25T17:42:24.4252512Z Exit code: -3
    2015-08-25T17:42:24.4342512Z ##[error]Unexpected exit code -3 returned from tool Octo.exe

I can provide more details on request.

**Comment by Damovisa** [comment]
Hi @Quantumplation,

Apologies for the delay in replying, can you send an email to support@octopus.com with some more information?

Thanks,
Damo
