### ISSUE TITLE
OctopusPackNuGet@6 EISDIR error

### ISSUE THREAD

**Issue by kvpt** [OctopusDeploy/OctoTFS#296]
Hi,

I try to migrate the build pipeline to V6 but the pipeline fail on the step with this task.
I pass the same parameters as OctopusPack@4 which succeeded.

Here the log:
> 2023-02-22T16:36:29.3302019Z ##[section]Starting: Octopus Pack
2023-02-22T16:36:29.3308089Z ==============================================================================
2023-02-22T16:36:29.3308325Z Task         : Package Application for Octopus - NuGet
2023-02-22T16:36:29.3308501Z Description  : Package your application into a NuGet file.
2023-02-22T16:36:29.3308680Z Version      : 6.0.465
2023-02-22T16:36:29.3308821Z Author       : Octopus Deploy
2023-02-22T16:36:29.3308981Z Help         : Version: 6.0.465. [More Information](https://g.octopushq.com/TFS-VSTS)
2023-02-22T16:36:29.3309191Z ==============================================================================
2023-02-22T16:36:29.5458132Z ##[error]"Failed to execute pack. EISDIR: illegal operation on a directory, read
Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (node:fs:742:3)
    at tryReadSync (node:fs:442:20)
    at Object.readFileSync (node:fs:488:19)
    at YS (/home/vsts/work/_tasks/OctopusPackNuGet_72e7a1b6-19bc-48e6-8d20-a81f201d65a3/6.0.465/index.js:50:18418)
    at Gz (/home/vsts/work/_tasks/OctopusPackNuGet_72e7a1b6-19bc-48e6-8d20-a81f201d65a3/6.0.465/index.js:50:18593)
    at Object.<anonymous> (/home/vsts/work/_tasks/OctopusPackNuGet_72e7a1b6-19bc-48e6-8d20-a81f201d65a3/6.0.465/index.js:50:19079)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
2023-02-22T16:36:29.5476124Z ##[section]Finishing: Octopus Pack

**Comment by benPearce1** [comment]
@kvpt v6 changed the underlying framework we use for these tasks from the OctopusCLI to a nodejs application.
Are you able to provide me with a list of the directory structure that you are trying to pack?

**Comment by paatas** [comment]
I had the same issue. Havent done much further testing but if i omit the 'NuGetReleaseNotesFile"-parameter i get the error, passing in a valid file will work though.
So it seems it tries to read the file even though no file has been specified:

https://github.com/OctopusDeploy/OctoTFS/blob/3e38c71a19d1d2abe9247bd5f269eba07323a3fc/source/tasks/PackNuGet/PackNuGetV6/create-package.ts#L30-L32

**Comment by rikrak** [comment]
Setting the NuGetReleaseNotesFile fixed it for me too.  The parameter is marked as optional, maybe it's actually required?

**Comment by MarkDerman** [comment]
I am also getting this error.

I tried seeing if setting the NugetReleaseNotes property would circumnavigate the problem but it does not.

I can confirm that setting NuGetReleaseNotesFile also fixed it for me too.

IMHO this is a bug, as both NuGetReleaseNotesFile and NuGetReleaseNotes should be optional.
