### ISSUE TITLE
Certificate error with v6 tasks

### ISSUE THREAD

**Issue by dixy** [OctopusDeploy/OctoTFS#299]
I try to migrate v5 tasks to v6, but there is an error during the connection to the Octopus Deploy server.

```
2023-03-15T10:39:48.5790955Z ##[section]Starting: Push Package to Octopus
2023-03-15T10:39:48.6089532Z ==============================================================================
2023-03-15T10:39:48.6089809Z Task         : Push Package(s) to Octopus
2023-03-15T10:39:48.6090098Z Description  : Push your NuGet or Zip package to your Octopus Deploy Server. **v6 of this step requires Octopus 2022.3+**
2023-03-15T10:39:48.6090376Z Version      : 6.0.502
2023-03-15T10:39:48.6090540Z Author       : Octopus Deploy
2023-03-15T10:39:48.6090776Z Help         : Version: 6.0.502. [More Information](https://g.octopushq.com/TFS-VSTS)
2023-03-15T10:39:48.6091058Z ==============================================================================
2023-03-15T10:39:48.9160922Z ##[error]"Failed to execute push. unable to get local issuer certificate
Error: unable to get local issuer certificate
    at Function.ae.from (F:\agent3\_work\_tasks\OctopusPush_d05ad9a2-5d9e-4a1c-a887-14034334d6f2\6.0.502\index.js:42:13882)
    at en.<anonymous> (F:\agent3\_work\_tasks\OctopusPush_d05ad9a2-5d9e-4a1c-a887-14034334d6f2\6.0.502\index.js:44:10223)
    at en.emit (node:events:527:28)
    at ClientRequest.Tf.<computed> (F:\agent3\_work\_tasks\OctopusPush_d05ad9a2-5d9e-4a1c-a887-14034334d6f2\6.0.502\index.js:42:738)
    at ClientRequest.emit (node:events:527:28)
    at TLSSocket.socketErrorListener (node:_http_client:454:9)
    at TLSSocket.emit (node:events:527:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
2023-03-15T10:39:48.9252160Z ##[section]Finishing: Push Package to Octopus
```

The certificate used on the Octopus Deploy server is signed by an internal CA.

Currently it is not possible to provide a CA file in Octo tasks, maybe a parameter that contains a path to a CA file on the server will help.

**Comment by benPearce1** [comment]
@dixy where is the agent located for this failed task? internal or Microsoft hosted?

**Comment by dixy** [comment]
@benPearce1 the agent is on an internal server
