### ISSUE TITLE
V6 Azure Devops Plugin fails to create release when version control enabled on project.

### ISSUE THREAD

**Issue by DavidIngham-Servelec** [OctopusDeploy/OctoTFS#300]
**Octopus Version:** v2022.4 (Build 8319)

**Problem Description:**
I'm converting some of our build pipelines to run in Azure DevOps Cloud. Our build creates several components all of which the v6 plugin is able to create releases for. The last component release however has version control information specified and this fails to create the release with the following error:

**Error Detail:**
```
==============================================================================
Task         : Create Octopus Release
Description  : Create a Release in Octopus Deploy
Version      : 6.0.502
Author       : Octopus Deploy
Help         : Version: 6.0.502. [More Information](https://g.octopushq.com/TFS-VSTS)
==============================================================================
🐙 Creating a release in Octopus Deploy...
##[error]"Failed to execute command. The Resource field is required.
Error: The Resource field is required.
    at new t (E:\AZDO\1\_work\_tasks\OctopusCreateRelease_4e131b60-5532-4362-95b6-7c67d9841b4f\6.0.502\index.js:1:5506)
    at EM (E:\AZDO\1\_work\_tasks\OctopusCreateRelease_4e131b60-5532-4362-95b6-7c67d9841b4f\6.0.502\index.js:45:3562)
    at e.handleError (E:\AZDO\1\_work\_tasks\OctopusCreateRelease_4e131b60-5532-4362-95b6-7c67d9841b4f\6.0.502\index.js:45:2758)
    at e.<anonymous> (E:\AZDO\1\_work\_tasks\OctopusCreateRelease_4e131b60-5532-4362-95b6-7c67d9841b4f\6.0.502\index.js:45:3341)
    at m (E:\AZDO\1\_work\_tasks\OctopusCreateRelease_4e131b60-5532-4362-95b6-7c67d9841b4f\6.0.502\index.js:45:2215)
    at Object.throw (E:\AZDO\1\_work\_tasks\OctopusCreateRelease_4e131b60-5532-4362-95b6-7c67d9841b4f\6.0.502\index.js:45:1498)
    at m (E:\AZDO\1\_work\_tasks\OctopusCreateRelease_4e131b60-5532-4362-95b6-7c67d9841b4f\6.0.502\index.js:45:1107)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
##[error]"Failed to successfully create release. The Resource field is required.
Error: The Resource field is required.
    at new t (E:\AZDO\1\_work\_tasks\OctopusCreateRelease_4e131b60-5532-4362-95b6-7c67d9841b4f\6.0.502\index.js:1:5506)
    at EM (E:\AZDO\1\_work\_tasks\OctopusCreateRelease_4e131b60-5532-4362-95b6-7c67d9841b4f\6.0.502\index.js:45:3562)
    at e.handleError (E:\AZDO\1\_work\_tasks\OctopusCreateRelease_4e131b60-5532-4362-95b6-7c67d9841b4f\6.0.502\index.js:45:2758)
    at e.<anonymous> (E:\AZDO\1\_work\_tasks\OctopusCreateRelease_4e131b60-5532-4362-95b6-7c67d9841b4f\6.0.502\index.js:45:3341)
    at m (E:\AZDO\1\_work\_tasks\OctopusCreateRelease_4e131b60-5532-4362-95b6-7c67d9841b4f\6.0.502\index.js:45:2215)
    at Object.throw (E:\AZDO\1\_work\_tasks\OctopusCreateRelease_4e131b60-5532-4362-95b6-7c67d9841b4f\6.0.502\index.js:45:1498)
    at m (E:\AZDO\1\_work\_tasks\OctopusCreateRelease_4e131b60-5532-4362-95b6-7c67d9841b4f\6.0.502\index.js:45:1107)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
##[error]Unhandled: The Resource field is required.
##[error]Error: The Resource field is required.
    at new t (E:\AZDO\1\_work\_tasks\OctopusCreateRelease_4e131b60-5532-4362-95b6-7c67d9841b4f\6.0.502\index.js:1:5506)
    at EM (E:\AZDO\1\_work\_tasks\OctopusCreateRelease_4e131b60-5532-4362-95b6-7c67d9841b4f\6.0.502\index.js:45:3562)
    at e.handleError (E:\AZDO\1\_work\_tasks\OctopusCreateRelease_4e131b60-5532-4362-95b6-7c67d9841b4f\6.0.502\index.js:45:2758)
    at e.<anonymous> (E:\AZDO\1\_work\_tasks\OctopusCreateRelease_4e131b60-5532-4362-95b6-7c67d9841b4f\6.0.502\index.js:45:3341)
    at m (E:\AZDO\1\_work\_tasks\OctopusCreateRelease_4e131b60-5532-4362-95b6-7c67d9841b4f\6.0.502\index.js:45:2215)
    at Object.throw (E:\AZDO\1\_work\_tasks\OctopusCreateRelease_4e131b60-5532-4362-95b6-7c67d9841b4f\6.0.502\index.js:45:1498)
    at m (E:\AZDO\1\_work\_tasks\OctopusCreateRelease_4e131b60-5532-4362-95b6-7c67d9841b4f\6.0.502\index.js:45:1107)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by benPearce1** [comment]
Hi @DaveIngham-AccessGroup,

This issue may be caused by the server being case sensitive when finding the project or channel. We have fixes that address this issue, which would require you to upgrade your server.

Can you check that the project/channel names exactly match the names in your Octopus instance?

**Comment by DaveIngham-AccessGroup** [comment]
Thank you! Yes on that project who ever had made that one called it 'Dev channel' instead of 'Dev Channel'.  

Resolved now thank you.
