### ISSUE TITLE
[ERR_FS_FILE_TOO_LARGE] on Push Package(s) to Octopus 

### ISSUE THREAD

**Issue by aguacongas** [OctopusDeploy/OctoTFS#324]
The  Push Package(s) to Octopus step fail with error : 

```
Starting: push_to_octopus
==============================================================================
Task         : Push Package(s) to Octopus
Description  : Push your NuGet or Zip package to your Octopus Deploy Server. **v6 of this step requires Octopus 2022.3+**
Version      : 6.0.599
Author       : Octopus Deploy
Help         : Version: 6.0.599. [More Information](https://g.octopushq.com/TFS-VSTS)
==============================================================================
Uploading package, WSO2.20240116.24.nupkg...
##[error]"Failed to execute push. RangeError [ERR_FS_FILE_TOO_LARGE]: File size (2394962902) is greater than 2 GiB
Error: RangeError [ERR_FS_FILE_TOO_LARGE]: File size (2394962902) is greater than 2 GiB
    at e.<anonymous> (E:\TFS\Agents\DefaultAgent5\_work\_tasks\OctopusPush_d05ad9a2-5d9e-4a1c-a887-14034334d6f2\6.0.599\index.js:18:11434)
    at d (E:\TFS\Agents\DefaultAgent5\_work\_tasks\OctopusPush_d05ad9a2-5d9e-4a1c-a887-14034334d6f2\6.0.599\index.js:18:8997)
    at Object.next (E:\TFS\Agents\DefaultAgent5\_work\_tasks\OctopusPush_d05ad9a2-5d9e-4a1c-a887-14034334d6f2\6.0.599\index.js:18:8280)
    at p (E:\TFS\Agents\DefaultAgent5\_work\_tasks\OctopusPush_d05ad9a2-5d9e-4a1c-a887-14034334d6f2\6.0.599\index.js:18:7838)
Finishing: push_to_octopus

```

**Comment by benPearce1** [comment]
@aguacongas this issue is due to a limitation in NodeJS which limits the size that the process can read into memory.

As a workaround, you can use the Octopus CLI to upload the package. You will need to add two new steps to your process.

First add a `OctoInstaller@6` to install the cli on your agent, then add a script step.
The script will be: `octopus package upload --space <space name> --package <package filename> --no-prompt`
It will also require the following environment variables to be set: `OCTOPUS_URL` and `OCTOPUS_API_KEY`

**Comment by michelle-luana** [comment]
The Octopus engineering team has reviewed this issue.  
After careful consideration, we’ve classed this low priority. This means we won’t work on it in the near future. 
We prioritize issues based on the number of people affected, the impact type, and available workarounds. 
If you’ve encountered this issue and haven’t informed our support team, please email [support@octopus.com](mailto:support@octopus.com). Knowing how many people this issue affects helps us determine its priority.
