### ISSUE TITLE
OctopusCreateRelease@6 - Failed to execute command. Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by BrianRichardson** [OctopusDeploy/OctoTFS#328]
### Build Pipeline Task Definition
```
- task: OctopusCreateRelease@6
  displayName: "Create Octopus Release"
  inputs:
    ReleaseNumber: "$(Build.BuildNumber)"
    ReleaseNotes: "Branch: $(Build.SourceBranch)"
    Project: "${{ parameters.OctopusProjectName }}"
    Channel: "${{ parameters.OctopusChannelName }}"
    Space: "${{ parameters.OctopusSpaceName }}"
    OctoConnectedServiceName: "$(Octopus-ServiceConnection)"

```

### Task Output
2024-09-25T09:16:06.1973974Z ##[debug]Evaluating condition for step: 'Create Octopus Release'
2024-09-25T09:16:06.1974636Z ##[debug]Evaluating: SucceededNode()
2024-09-25T09:16:06.1974820Z ##[debug]Evaluating SucceededNode:
2024-09-25T09:16:06.1975163Z ##[debug]=> True
2024-09-25T09:16:06.1975347Z ##[debug]Result: True
2024-09-25T09:16:06.1975546Z ##[section]Starting: Create Octopus Release
2024-09-25T09:16:06.1978738Z ==============================================================================
2024-09-25T09:16:06.1978826Z Task         : Create Octopus Release
2024-09-25T09:16:06.1978882Z Description  : Create a Release in Octopus Deploy
2024-09-25T09:16:06.1978957Z Version      : 6.0.750
2024-09-25T09:16:06.1979019Z Author       : Octopus Deploy
2024-09-25T09:16:06.1979080Z Help         : Version: 6.0.750. [More Information](https://g.octopushq.com/TFS-VSTS)
2024-09-25T09:16:06.1979159Z ==============================================================================
2024-09-25T09:16:06.2008189Z ##[debug]Resource Utilization warnings is disabled, switch "DISABLE_RESOURCE_UTILIZATION_WARNINGS" variable to "false" if you want to enable it
2024-09-25T09:16:06.2361879Z ##[debug]Using node path: /agent/externals/node16/bin/node
2024-09-25T09:16:06.3377376Z ##[debug]agent.TempDirectory=/agent/_work/_temp
2024-09-25T09:16:06.3384625Z ##[debug]loading inputs and endpoints
2024-09-25T09:16:06.3388896Z ##[debug]loading INPUT_OCTOCONNECTEDSERVICENAME
2024-09-25T09:16:06.3396783Z ##[debug]loading INPUT_SPACE
2024-09-25T09:16:06.3397734Z ##[debug]loading INPUT_PROJECT
2024-09-25T09:16:06.3399309Z ##[debug]loading INPUT_RELEASENUMBER
2024-09-25T09:16:06.3400094Z ##[debug]loading INPUT_CHANNEL
2024-09-25T09:16:06.3401395Z ##[debug]loading INPUT_RELEASENOTES
2024-09-25T09:16:06.3403032Z ##[debug]loading ENDPOINT_AUTH_862ec503-7db5-4a7c-bffa-cac6607bf0bd
2024-09-25T09:16:06.3405755Z ##[debug]loading ENDPOINT_AUTH_SCHEME_862ec503-7db5-4a7c-bffa-cac6607bf0bd
2024-09-25T09:16:06.3406632Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_862ec503-7db5-4a7c-bffa-cac6607bf0bd_APITOKEN
2024-09-25T09:16:06.3408938Z ##[debug]loading ENDPOINT_AUTH_SYSTEMVSSCONNECTION
2024-09-25T09:16:06.3411536Z ##[debug]loading ENDPOINT_AUTH_SCHEME_SYSTEMVSSCONNECTION
2024-09-25T09:16:06.3414216Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_SYSTEMVSSCONNECTION_ACCESSTOKEN
2024-09-25T09:16:06.3418912Z ##[debug]loading SECRET_SYSTEM_ACCESSTOKEN
2024-09-25T09:16:06.3420787Z ##[debug]loaded 13
2024-09-25T09:16:06.3431396Z ##[debug]Agent.ProxyUrl=undefined
2024-09-25T09:16:06.3431909Z ##[debug]Agent.CAInfo=undefined
2024-09-25T09:16:06.3432371Z ##[debug]Agent.ClientCert=undefined
2024-09-25T09:16:06.3432847Z ##[debug]Agent.SkipCertValidation=undefined
2024-09-25T09:16:06.4190009Z ##[debug]OctoConnectedServiceName=862ec503-7db5-4a7c-bffa-cac6607bf0bd
2024-09-25T09:16:06.4191131Z ##[debug]862ec503-7db5-4a7c-bffa-cac6607bf0bd exists true
2024-09-25T09:16:06.4192432Z ##[debug]862ec503-7db5-4a7c-bffa-cac6607bf0bd data ignoreSslErrors = true
2024-09-25T09:16:06.4193630Z ##[debug]862ec503-7db5-4a7c-bffa-cac6607bf0bd=https://_fictional-octopus-server_.com/
2024-09-25T09:16:06.4196750Z ##[debug]AdditionalArguments=undefined
2024-09-25T09:16:06.4197329Z ##[debug]AdditionalArguments:undefined
2024-09-25T09:16:06.4197934Z ##[debug]Packages=undefined
2024-09-25T09:16:06.4198404Z ##[debug]Packages:undefined
2024-09-25T09:16:06.4198872Z ##[debug]DefaultPackageVersion=undefined
2024-09-25T09:16:06.4199435Z ##[debug]Space=_FictionalSpace_
2024-09-25T09:16:06.4199903Z ##[debug]Project=_FictionalProject_
2024-09-25T09:16:06.4200792Z ##[debug]ReleaseNumber=1.0.0-main-alpha-20240925091434
2024-09-25T09:16:06.4201568Z ##[debug]Channel=_FictionalChannel_
2024-09-25T09:16:06.4202556Z ##[debug]ReleaseNotes=Branch: refs/heads/main
2024-09-25T09:16:06.4203044Z ##[debug]GitRef=undefined
2024-09-25T09:16:06.4203506Z ##[debug]GitCommit=undefined
2024-09-25T09:16:06.4203957Z ##[debug]ReleaseNotesFile=undefined
2024-09-25T09:16:06.4204538Z ##[debug]{"spaceName":"_FictionalSpace_","ProjectName":"_FictionalProject_","ReleaseVersion":"1.0.0-main-alpha-20240925091434","ChannelName":"_FictionalChannel_","ReleaseNotes":"Branch: refs/heads/main"}
2024-09-25T09:16:06.6505108Z 🐙 Creating a release in Octopus Deploy...
2024-09-25T09:16:06.6514019Z ##[debug]Creating a release...
2024-09-25T09:16:06.6518770Z ##[debug]Resolving space from name '_FictionalSpace_'
2024-09-25T09:16:06.8738752Z ##[debug]Resolved space name '_FictionalSpace_' to Id Spaces-1
2024-09-25T09:16:07.2456923Z ##[debug]task result: Failed
2024-09-25T09:16:07.2494783Z ##[error]"Failed to execute command. Object reference not set to an instance of an object.
Error: Object reference not set to an instance of an object.
    at new t (/agent/_work/_tasks/OctopusCreateRelease_4e131b60-5532-4362-95b6-7c67d9841b4f/6.0.750/index.js:1:5506)
    at hX (/agent/_work/_tasks/OctopusCreateRelease_4e131b60-5532-4362-95b6-7c67d9841b4f/6.0.750/index.js:45:3562)
    at e.handleError (/agent/_work/_tasks/OctopusCreateRelease_4e131b60-5532-4362-95b6-7c67d9841b4f/6.0.750/index.js:45:2758)
    at e.<anonymous> (/agent/_work/_tasks/OctopusCreateRelease_4e131b60-5532-4362-95b6-7c67d9841b4f/6.0.750/index.js:45:3341)
    at u (/agent/_work/_tasks/OctopusCreateRelease_4e131b60-5532-4362-95b6-7c67d9841b4f/6.0.750/index.js:45:2215)
    at Object.throw (/agent/_work/_tasks/OctopusCreateRelease_4e131b60-5532-4362-95b6-7c67d9841b4f/6.0.750/index.js:45:1498)
    at u (/agent/_work/_tasks/OctopusCreateRelease_4e131b60-5532-4362-95b6-7c67d9841b4f/6.0.750/index.js:45:1107)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
2024-09-25T09:16:07.2503829Z ##[debug]Processed: ##vso[task.issue type=error;]"Failed to execute command. Object reference not set to an instance of an object.
Error: Object reference not set to an instance of an object.
    at new t (/agent/_work/_tasks/OctopusCreateRelease_4e131b60-5532-4362-95b6-7c67d9841b4f/6.0.750/index.js:1:5506)
    at hX (/agent/_work/_tasks/OctopusCreateRelease_4e131b60-5532-4362-95b6-7c67d9841b4f/6.0.750/index.js:45:3562)
    at e.handleError (/agent/_work/_tasks/OctopusCreateRelease_4e131b60-5532-4362-95b6-7c67d9841b4f/6.0.750/index.js:45:2758)
    at e.<anonymous> (/agent/_work/_tasks/OctopusCreateRelease_4e131b60-5532-4362-95b6-7c67d9841b4f/6.0.750/index.js:45:3341)
    at u (/agent/_work/_tasks/OctopusCreateRelease_4e131b60-5532-4362-95b6-7c67d9841b4f/6.0.750/index.js:45:2215)
    at Object.throw (/agent/_work/_tasks/OctopusCreateRelease_4e131b60-5532-4362-95b6-7c67d9841b4f/6.0.750/index.js:45:1498)
    at u (/agent/_work/_tasks/OctopusCreateRelease_4e131b60-5532-4362-95b6-7c67d9841b4f/6.0.750/index.js:45:1107)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
2024-09-25T09:16:07.2511020Z ##[debug]Processed: ##vso[task.complete result=Failed;done=true;]"Failed to execute command. Object reference not set to an instance of an object.
Error: Object reference not set to an instance of an object.
    at new t (/agent/_work/_tasks/OctopusCreateRelease_4e131b60-5532-4362-95b6-7c67d9841b4f/6.0.750/index.js:1:5506)
    at hX (/agent/_work/_tasks/OctopusCreateRelease_4e131b60-5532-4362-95b6-7c67d9841b4f/6.0.750/index.js:45:3562)
    at e.handleError (/agent/_work/_tasks/OctopusCreateRelease_4e131b60-5532-4362-95b6-7c67d9841b4f/6.0.750/index.js:45:2758)
    at e.<anonymous> (/agent/_work/_tasks/OctopusCreateRelease_4e131b60-5532-4362-95b6-7c67d9841b4f/6.0.750/index.js:45:3341)
    at u (/agent/_work/_tasks/OctopusCreateRelease_4e131b60-5532-4362-95b6-7c67d9841b4f/6.0.750/index.js:45:2215)
    at Object.throw (/agent/_work/_tasks/OctopusCreateRelease_4e131b60-5532-4362-95b6-7c67d9841b4f/6.0.750/index.js:45:1498)
    at u (/agent/_work/_tasks/OctopusCreateRelease_4e131b60-5532-4362-95b6-7c67d9841b4f/6.0.750/index.js:45:1107)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
2024-09-25T09:16:07.2511980Z ##[debug]task result: Failed
2024-09-25T09:16:07.2513481Z ##[error]"Failed to successfully create release. Object reference not set to an instance of an object.
Error: Object reference not set to an instance of an object.
    at new t (/agent/_work/_tasks/OctopusCreateRelease_4e131b60-5532-4362-95b6-7c67d9841b4f/6.0.750/index.js:1:5506)
    at hX (/agent/_work/_tasks/OctopusCreateRelease_4e131b60-5532-4362-95b6-7c67d9841b4f/6.0.750/index.js:45:3562)
    at e.handleError (/agent/_work/_tasks/OctopusCreateRelease_4e131b60-5532-4362-95b6-7c67d9841b4f/6.0.750/index.js:45:2758)
    at e.<anonymous> (/agent/_work/_tasks/OctopusCreateRelease_4e131b60-5532-4362-95b6-7c67d9841b4f/6.0.750/index.js:45:3341)
    at u (/agent/_work/_tasks/OctopusCreateRelease_4e131b60-5532-4362-95b6-7c67d9841b4f/6.0.750/index.js:45:2215)
    at Object.throw (/agent/_work/_tasks/OctopusCreateRelease_4e131b60-5532-4362-95b6-7c67d9841b4f/6.0.750/index.js:45:1498)
    at u (/agent/_work/_tasks/OctopusCreateRelease_4e131b60-5532-4362-95b6-7c67d9841b4f/6.0.750/index.js:45:1107)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
2024-09-25T09:16:07.2514980Z ##[debug]Processed: ##vso[task.issue type=error;]"Failed to successfully create release. Object reference not set to an instance of an object.
Error: Object reference not set to an instance of an object.
    at new t (/agent/_work/_tasks/OctopusCreateRelease_4e131b60-5532-4362-95b6-7c67d9841b4f/6.0.750/index.js:1:5506)
    at hX (/agent/_work/_tasks/OctopusCreateRelease_4e131b60-5532-4362-95b6-7c67d9841b4f/6.0.750/index.js:45:3562)
    at e.handleError (/agent/_work/_tasks/OctopusCreateRelease_4e131b60-5532-4362-95b6-7c67d9841b4f/6.0.750/index.js:45:2758)
    at e.<anonymous> (/agent/_work/_tasks/OctopusCreateRelease_4e131b60-5532-4362-95b6-7c67d9841b4f/6.0.750/index.js:45:3341)
    at u (/agent/_work/_tasks/OctopusCreateRelease_4e131b60-5532-4362-95b6-7c67d9841b4f/6.0.750/index.js:45:2215)
    at Object.throw (/agent/_work/_tasks/OctopusCreateRelease_4e131b60-5532-4362-95b6-7c67d9841b4f/6.0.750/index.js:45:1498)
    at u (/agent/_work/_tasks/OctopusCreateRelease_4e131b60-5532-4362-95b6-7c67d9841b4f/6.0.750/index.js:45:1107)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
2024-09-25T09:16:07.2516810Z ##[debug]Processed: ##vso[task.complete result=Failed;done=true;]"Failed to successfully create release. Object reference not set to an instance of an object.
Error: Object reference not set to an instance of an object.
    at new t (/agent/_work/_tasks/OctopusCreateRelease_4e131b60-5532-4362-95b6-7c67d9841b4f/6.0.750/index.js:1:5506)
    at hX (/agent/_work/_tasks/OctopusCreateRelease_4e131b60-5532-4362-95b6-7c67d9841b4f/6.0.750/index.js:45:3562)
    at e.handleError (/agent/_work/_tasks/OctopusCreateRelease_4e131b60-5532-4362-95b6-7c67d9841b4f/6.0.750/index.js:45:2758)
    at e.<anonymous> (/agent/_work/_tasks/OctopusCreateRelease_4e131b60-5532-4362-95b6-7c67d9841b4f/6.0.750/index.js:45:3341)
    at u (/agent/_work/_tasks/OctopusCreateRelease_4e131b60-5532-4362-95b6-7c67d9841b4f/6.0.750/index.js:45:2215)
    at Object.throw (/agent/_work/_tasks/OctopusCreateRelease_4e131b60-5532-4362-95b6-7c67d9841b4f/6.0.750/index.js:45:1498)
    at u (/agent/_work/_tasks/OctopusCreateRelease_4e131b60-5532-4362-95b6-7c67d9841b4f/6.0.750/index.js:45:1107)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
2024-09-25T09:16:07.2517691Z ##[debug]task result: Failed
2024-09-25T09:16:07.2518130Z ##[error]Unhandled: Object reference not set to an instance of an object.
2024-09-25T09:16:07.2518416Z ##[debug]Processed: ##vso[task.issue type=error;]Unhandled: Object reference not set to an instance of an object.
2024-09-25T09:16:07.2518973Z ##[debug]Processed: ##vso[task.complete result=Failed;]Unhandled: Object reference not set to an instance of an object.
2024-09-25T09:16:07.2520321Z ##[error]Error: Object reference not set to an instance of an object.
    at new t (/agent/_work/_tasks/OctopusCreateRelease_4e131b60-5532-4362-95b6-7c67d9841b4f/6.0.750/index.js:1:5506)
    at hX (/agent/_work/_tasks/OctopusCreateRelease_4e131b60-5532-4362-95b6-7c67d9841b4f/6.0.750/index.js:45:3562)
    at e.handleError (/agent/_work/_tasks/OctopusCreateRelease_4e131b60-5532-4362-95b6-7c67d9841b4f/6.0.750/index.js:45:2758)
    at e.<anonymous> (/agent/_work/_tasks/OctopusCreateRelease_4e131b60-5532-4362-95b6-7c67d9841b4f/6.0.750/index.js:45:3341)
    at u (/agent/_work/_tasks/OctopusCreateRelease_4e131b60-5532-4362-95b6-7c67d9841b4f/6.0.750/index.js:45:2215)
    at Object.throw (/agent/_work/_tasks/OctopusCreateRelease_4e131b60-5532-4362-95b6-7c67d9841b4f/6.0.750/index.js:45:1498)
    at u (/agent/_work/_tasks/OctopusCreateRelease_4e131b60-5532-4362-95b6-7c67d9841b4f/6.0.750/index.js:45:1107)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
2024-09-25T09:16:07.2521741Z ##[debug]Processed: ##vso[task.issue type=error;]Error: Object reference not set to an instance of an object.
    at new t (/agent/_work/_tasks/OctopusCreateRelease_4e131b60-5532-4362-95b6-7c67d9841b4f/6.0.750/index.js:1:5506)
    at hX (/agent/_work/_tasks/OctopusCreateRelease_4e131b60-5532-4362-95b6-7c67d9841b4f/6.0.750/index.js:45:3562)
    at e.handleError (/agent/_work/_tasks/OctopusCreateRelease_4e131b60-5532-4362-95b6-7c67d9841b4f/6.0.750/index.js:45:2758)
    at e.<anonymous> (/agent/_work/_tasks/OctopusCreateRelease_4e131b60-5532-4362-95b6-7c67d9841b4f/6.0.750/index.js:45:3341)
    at u (/agent/_work/_tasks/OctopusCreateRelease_4e131b60-5532-4362-95b6-7c67d9841b4f/6.0.750/index.js:45:2215)
    at Object.throw (/agent/_work/_tasks/OctopusCreateRelease_4e131b60-5532-4362-95b6-7c67d9841b4f/6.0.750/index.js:45:1498)
    at u (/agent/_work/_tasks/OctopusCreateRelease_4e131b60-5532-4362-95b6-7c67d9841b4f/6.0.750/index.js:45:1107)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
2024-09-25T09:16:07.2543759Z ##[section]Finishing: Create Octopus Release

**Comment by davidroberts63** [comment]
We just experienced this as well today, very similar. Though different line:column number in the compress js. 
We had a CaC project that was brand new, no deployments, runbooks, or releases.

We are not 100% sure but we know it one or more of the following may resolve this:

* Create a release manually. Perhaps some logic was tripping over a lack of prior releases? (Low confidence in this)
* Disable any steps that reference a nuget package. In our case the package didn't exist in the feed. (Very high confidence this was the actual problem).

Having said that, the error of 'Object reference not set' could really use some improvement to be helpful to users.
